[sim_hit_reading]
particleZ = [-3000, 3000]
particleR = [0, 1150]

[simulation]

minimal_kinetic_energy = 0.1
user_particle_handler = "default"

[digitization]
# config_file = "config/odd-digi-smearing-config.json"
config_file = "config/odd-digi-geometric-config.json"
